spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    # h2 연동
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:~/test;"
    username: sa
    password:

#    # mariaDB 연동
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/clone_carrot?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: sk305692*