spring:
  datasource:
    # h2 연동
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    initialization-mode: always
    sql-script-encoding: UTF-8

  #    # mariaDB 연동
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/clone_carrot?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: sk305692*

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console